kind: pipeline
type: docker
name: frontend
steps:
  - name: build
    image: node:14.17.1
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm run build
trigger:
  branch:
    - master
  event:
    - push
